[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
cache = true
cache_path = 'cache'
broadcast = 'broadcast'
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/','@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/','@chainlink/contracts/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/','@uniswap/v4-core/=lib/v4-core/','solmate/=lib/v4-core/lib/solmate/','@uniswap/v4-periphery/=lib/v4-periphery/']

[profile.solx]
solc_version = "/home/hacker/.local/bin/solx"


[fuzz]
runs = 1000
show_metrics = true
fail_on_revert = true
max_test_rejects = 65536

[invariant]
runs = 128
depth = 128
show_metrics = true
fail_on_revert = true
show_progress = true


fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
